Fix cudaErrorInvalidValue in groupBy SHMEM calculation (Devtech-Compute/gqe!398)
## Goal and reason

Fixes a bug `hash_groupby.cuh` which occurred only when running with `DEBUG` build type.

## Problem statement

Call to cuda API `cuOccupancyAvailableDynamicSMemPerBlock` needs to ensure that the `numBlocks` parameter is valid to be scheduled on a SM. i.e. We need to ensure that for the case when we use 0 KB of shared memory, the number of blocks passed to the function can actually fit on the SM.

## Solution approach

MR adds a check to find the max active blocks per SM assuming 0 KB shared memory usage, and takes a min of the block which we would like to schedule on a SM and blocks which can be scheduled

## Alternative approaches

_N/A_

## Impact (feature / bug / performance)

Fixes a bug which occurs when running TPCH Q10 with SF1k dataset in debug mode.

```
Running query from substrait with parameters debug_mem_usage=False, QueryExecutionContext(num_workers=8, num_partitions=8, use_overlap_mtx=True, join_use_hash_map_cache=True, read_use_zero_copy=False, join_use_unique_keys=True, join_use_perfect_hash=False, join_use_mark_join=False, use_partition_pruning=False, filter_use_like_shift_and=True, aggregation_use_perfect_hash=False, sut_info_id=None, query_info_ctx=QueryInfoContext(query_idx=10, query_str='10', query_source='substrait', reference_file='/tpch/reference_results/sf1000/q10', scale_factor=1000.0, substrait_file='/tpch/substrait_plans/df_q10.bin', physical_plan_folder=None)), DataInfo(num_row_groups=8, compression_format='none', compression_data_type='char', compression_chunk_size=65536, zone_map_partition_size=100000, data_info_id=1, storage_device_kind='numa_pinned_memory', format='internal', location=None, not_null=False, identifier_type='TypeId.int64', char_type='char', decimal_type='float')
No load required - data already in memory
[2025-11-18 16:08:47.077] [gqe] [warning] Use FLOAT64 to represent a decimal literal
Building query execution context...
Running Q10...
Starting query Q10 repetition 0...
[2025-11-18 16:08:48.111] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 4, block_size: 128
[2025-11-18 16:08:48.111] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 4, block_size: 128
[2025-11-18 16:08:48.123] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 4, block_size: 128
[2025-11-18 16:08:48.191] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 4, block_size: 128
[2025-11-18 16:08:48.278] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 4, block_size: 128
[2025-11-18 16:08:48.368] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 4, block_size: 128
[2025-11-18 16:08:48.627] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 4, block_size: 128
[2025-11-18 16:08:48.880] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 4, block_size: 128
Error during query execution
RuntimeError: CUDA error at: /home/repos/gqe/src/executor/groupby/hash_groupby.cuh564: cudaErrorInvalidValue invalid argument
```

## Tests

Tested by rerunning TPCH Q10 in Debug mode and adding additional logging statements

```
Running query from handcoded with parameters debug_mem_usage=False, QueryExecutionContext(num_workers=8, num_partitions=8, use_overlap_mtx=True, join_use_hash_map_cache=True, read_use_zero_copy=False, join_use_unique_keys=True, join_use_perfect_hash=False, join_use_mark_join=False, use_partition_pruning=False, filter_use_like_shift_and=True, aggregation_use_perfect_hash=False, sut_info_id=None, query_info_ctx=QueryInfoContext(query_idx=10, query_str='10', query_source='handcoded', reference_file='/tpch/reference_results/sf1000/q10', scale_factor=1000.0, substrait_file=None, physical_plan_folder=None)), DataInfo(num_row_groups=8, compression_format='none', compression_data_type='char', compression_chunk_size=65536, zone_map_partition_size=100000, data_info_id=1, storage_device_kind='numa_pinned_memory', format='internal', location=None, not_null=False, identifier_type='TypeId.int64', char_type='char', decimal_type='float')
Attempting to load TPCH Query 10 data into memory
Building query execution context...
Running Q10...
Starting query Q10 repetition 0...
[2025-11-18 16:28:58.816] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 2, block_size: 128
[2025-11-18 16:28:58.901] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 2, block_size: 128
[2025-11-18 16:28:58.953] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 2, block_size: 128
[2025-11-18 16:28:59.006] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 2, block_size: 128
[2025-11-18 16:28:59.072] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 2, block_size: 128
[2025-11-18 16:28:59.162] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 2, block_size: 128
[2025-11-18 16:28:59.251] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 2, block_size: 128
[2025-11-18 16:28:59.338] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 2, block_size: 128
[2025-11-18 16:28:59.375] [gqe] [info] Calling cudaOccupancyAvailableDynamicSMemPerBlock with func ptr: 0xfffff51794c4, active_blocks_per_sm: 2, block_size: 128
Start verification...
```

## Review checklist

(to be signed off by the reviewer)

- [x] Assigned self as reviewer in GitLab sidebar.
- [x] MR branch is in the `DevTech-Compute/gqe` repository (i.e., not a fork), and is prefixed with `$user-`.
  - Exception: Author has not been granted write permissions.
- [x] MR title is ["syntactically correct"](https://cbea.ms/git-commit). E.g., "Optimize the aggregate operator for high group cardinality".
  - Less than 50 chars.
  - Capitalized.
  - Imperative mood.
  - Descriptive of the change.
- [x] MR goal, problem, and approach make sense to me (as described above).
- [x] MR is self-contained. I.e., doesn't rely on follow-up MRs to be minimially functional.
- [x] MR solves _one_ (sub-)issue. Big issue is split into multiple self-contained MRs.
- [x] All source code files include [the Apache-2.0 license header](https://confluence.nvidia.com/display/LEG/Apache+2.0) and year is up-to-date.
- [x] Code style adheres to the [C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines) and [libcudf developer guidelines](https://github.com/rapidsai/cudf/blob/main/cpp/doxygen/developer_guide/DEVELOPER_GUIDE.md).
  - MLIR code instead adheres to the [LLVM coding standards](https://llvm.org/docs/CodingStandards.html).
- [x] Code is DRY. I.e., uses existing GQE / cuDF / MLIR infrastructure and utilities.
- [x] Code is documented.
  - [Doxygen API comments](https://github.com/rapidsai/cudf/blob/main/cpp/doxygen/developer_guide/DOCUMENTATION.md).
  - Algorithm / data structure description (if relevant).
- [x] Code includes CI unit and/or integration tests (if relevant).
- [x] MR is tested (see section Tests) and doesn't break the gqe-python main branch.
- [x] Stale MR branches are cleaned up. E.g., `this-MR-branch-v1`.