fix: redefine a default argument in gqe::optimizer::projection_pushdown (Devtech-Compute/gqe!263)
# Motivation
When I tried to compile gqe on aarch64 (CG1) with CTK 12.8. It will fail due to `redefinition of default argument for 'class<template-parameter-1-2>'`:
```
/home/scratch.zhengruw_gpu/app/gqe_2412/src/optimizer/rules/projection_pushdown.cpp:134:23: error: redefinition of default argument for 'class<template-parameter-1-2>'
  134 | template <typename T, typename = std::enable_if_t<gqe::optimizer::optimizable_child_relation<T>()>>
      |                       ^~~~~~~~
In file included from /home/scratch.zhengruw_gpu/app/gqe_2412/src/optimizer/rules/projection_pushdown.cpp:16:
/home/scratch.zhengruw_gpu/app/gqe_2412/src/../include/gqe/optimizer/rules/projection_pushdown.hpp:62:25: note: original definition appeared here
   62 |   template <typename T, typename = std::enable_if_t<optimizable_child_relation<T>()>>
      |                         ^~~~~~~~
/home/scratch.zhengruw_gpu/app/gqe_2412/src/optimizer/rules/projection_pushdown.cpp:169:23: error: redefinition of default argument for 'class<template-parameter-1-2>'
  169 | template <typename T, typename = std::enable_if_t<gqe::optimizer::optimizable_child_relation<T>()>>
      |                       ^~~~~~~~
/home/scratch.zhengruw_gpu/app/gqe_2412/src/../include/gqe/optimizer/rules/projection_pushdown.hpp:66:25: note: original definition appeared here
   66 |   template <typename T, typename = std::enable_if_t<optimizable_child_relation<T>()>>
```
# How to fix
Remove default value in `src/optimizer/rules/projection_pushdown.cpp`
# Reference
- https://stackoverflow.com/questions/41515147/redefinition-of-default-argument-for-classtemplate-parameter-1-2
- https://en.cppreference.com/w/cpp/language/sfinae