Add MLIR to the Docker container (Devtech-Compute/gqe!191)
In preparation for query compiler prototyping, this MR adds MLIR to GQE's Docker container.

The Dockerfile builds MLIR from source, because the Conda `mlir` package is lacking features. Specifically:
 - The `mlir-opt` and `mlir-cpu-runner` commandline utilities are missing. These are used by [MLIR integration tests](https://github.com/llvm/llvm-project/blob/main/mlir/test/Integration/GPU/CUDA/printf.mlir), and useful for debugging.
 - CUDA integration is missing in `mlir-cpu-runner` and the C++ `mlir::ExecutionEngine`. This results in the error documented below.

The container is uploaded as `gitlab-master.nvidia.com:5005/devtech-compute/gqe:24.06-cuda12.2-mlir18.1.8-x86_64`. MLIR adds 12 min 22 secs build time.

## Missing CUDA in Conda `mlir`

Attempting to launch a GPU kernel in C++ using `mlir::ExecutionEngine` results in the error:

```sh
Failed to create MemoryBuffer for: /usr/local/lib/libmlir_cuda_runtime.so
Error: No such file or directory
Failed to create MemoryBuffer for: /usr/local/lib/libmlir_runner_utils.so
Error: No such file or directory
JIT session error: Symbols not found: [ mgpuLaunchKernel, mgpuModuleGetFunction, mgpuModuleLoad, mgpuModuleUnload, mgpuStreamCreate, mgpuStreamDestroy, mgpuStreamSynchronize ]
Failed to invoke code: Failed to materialize symbols: { (main, { _mlir_main, main }) }
```

The above issue is fixed in this Docker build.