Improve overlap using counting semaphores (Devtech-Compute/gqe!430)
## Goal and reason

We were hitting problems due to round-robin behavior in read tasks. Add counting semaphores to limit the number of threads that can execute each stage of the pipeline.

## Problem statement

*What is the concrete problem this MR solves towards achieving the stated goal?*

## Solution approach

*What is the solution proposed by this MR?*

## Alternative approaches

*What alternatives have you considered (if any)?*

## Impact (feature / bug / performance)

*What impact does this MR have? E.g., the new API features added. An example of
the buggy query result fixed. The measured speedup achieved. Support with
profiles, plots, tables, or logs (if relevant).*

## Issues closed

*The list of GQE issues this MR closes (if any).*

 - Closes #???
 - Closes #???

## Tests

*How was this MR tested? Consider relevant queries and scale factors for the
current phase of GQE development (e.g., TPC-H SF100, SF1k).*

### Performance

(Clemens)

#### Setup

 - SF1k (`sf1000_id64_clustered_by_month`)
 - GB200 (ptyche)
 - 2-level compression with CPU LZ4 level 10 and Cascaded
 - partition pruning enabled
 - gqe: `982e8998` (the current `main` on which this MR is based)
 - gqe-python: `836d6af`

#### Configuration

[gb200_sweep.json5](/uploads/b5dc95f6a6d0633d7002648470592895/gb200_sweep.json5)

```sh
rsync -rv --progress  /lustre/fsw/coreai_devtech_all/gqe/tpch/sf1000_id64_clustered_by_month /raid/scratch
./launch-docker.sh

export GQE_INITIAL_QUERY_MEMORY=178806325248
export GQE_MAX_QUERY_MEMORY=178806325248
export GQE_INITIAL_TASK_MANAGER_MEMORY=429496729600

git config --global url."https://clutz:[redacted]@gitlab-master.nvidia.com/".insteadOf "https://gitlab-master.nvidia.com/"
pip install -Cbuild-dir=/home/clutz/gqe-build -C cmake.define.GQE_SOURCE_DIR=/home/clutz/gqe -e /home/clutz/gqe-python

/home/clutz/gqe-python/gqe/benchmark/run_tpch_parameter_sweep.py --json /home/clutz/gqe-python/gb200_sweep.json5
```

#### GQE TOT Baseline

[gqe_main.db3](/uploads/16f70e888a9db4b98664ab2e3280db07/gqe_main.db3)

```
D select e_scale_factor, e_name, e_query_source, r_avg_duration_s, sample_size from gqe_best_parameters;
+----------------+--------+----------------+------------------+-------------+
| e_scale_factor | e_name | e_query_source | r_avg_duration_s | sample_size |
+----------------+--------+----------------+------------------+-------------+
| 1000.0         | Q4     | handcoded      | 0.2958236978     | 5           |
| 1000.0         | Q6     | handcoded      | 0.1610891342     | 5           |
| 1000.0         | Q21    | handcoded      | 1.470640502      | 5           |
+----------------+--------+----------------+------------------+-------------+
```

#### This MR

[gqe_semaphore.db3](/uploads/26e014487db977c85a8f3a97843806c1/gqe_semaphore.db3)

```
D select e_scale_factor, e_name, e_query_source, r_avg_duration_s, sample_size from gqe_best_parameters;
+----------------+--------+----------------+------------------+-------------+
| e_scale_factor | e_name | e_query_source | r_avg_duration_s | sample_size |
+----------------+--------+----------------+------------------+-------------+
| 1000.0         | Q4     | handcoded      | 0.2884214106     | 5           |
| 1000.0         | Q6     | handcoded      | 0.1599494658     | 5           |
| 1000.0         | Q21    | handcoded      | 1.324700224      | 1           |
+----------------+--------+----------------+------------------+-------------+
```

#### Observations

Improvement for these queries is marginal. Q21 crashes in 4 of 6 runs (6 runs, but sample size = 1).

Q9 failed to run, due to OOM. This occurred on TOT as well, thus unrelated to this MR.

### Avoid timeouts incurred by `std::counting_semaphore`

(Clemens)

I was not able to trigger timeouts with SF100. To reproduce timeouts seen by @tyallen on GB200 with SF1k, I instead inject an exception with a one-line patch.

[inject_exception.patch](/uploads/8b205b62b32a7fbb0635711c7815a41a/inject_exception.patch)

```diff
diff --git a/src/storage/in_memory.cpp b/src/storage/in_memory.cpp
index 92d0eee0..9d3222a7 100644
--- a/src/storage/in_memory.cpp
+++ b/src/storage/in_memory.cpp
@@ -1628,6 +1628,7 @@ void in_memory_read_task::emit_copied_result(std::unique_ptr<pruning_results_t>
     utility::nvtx_scoped_range nvtx_range("Decompressing columns");
     GQE_CUDA_TRY(cudaStreamSynchronize(decompression_stream));
     _decompress_semaphore.acquire();
+    throw std::runtime_error("Test exception to check if a hang occurs");
     for (auto& column_creator : output_columns) {
       bool was_compressed = column_creator->decompress_row_group_columns(decompression_stream);
       has_compressed_columns |= was_compressed;
```

Then I tested on my virtual dev machine with SF100 as follows:

 - gqe: this MR's feature branch
 - gqe-python: 9e079f8a8f63c51e3f450d60f15b1fd40c66473a

```sh
git config --global url."https://clutz:[redacted]@gitlab-master.nvidia.com/".insteadOf "https://gitlab-master.nvidia.com/"

git apply inject_exception.patch

pip install -Cbuild-dir=/root/gqedev/gqe-python/build -C cmake.define.GQE_SOURCE_DIR=/root/gqedev/gqe -e .
./gqe/benchmark/run_tpch_parameter_sweep.py --row-groups 32 --partitions 16 --sandboxing --workers 4 --compression-format ans --read-use-filter-pruning true --secondary-compression-format cascaded --query-timeout 240 --data-timeout 300 --queries 6 -- /scratch/local/tpch/sf100_chunk16m_id32 /home/gqe/tpch/substrait_plans /scratch/local/tpch/reference_results/sf100/%d.parquet 2>&1 | tee gqe.log
```

Directly using `semaphore.acquire()` and `semaphore.release()` results in the sequence:

1. two worker threads acquire the semaphore
2. these threads throw the exception
3. the other two workers are not able to acquire the semaphore and block indefinitely
4. timeout

After some rounds of this, I manually killed the experiment, as evident in the log file.

[gqe_direct_acquire.log](/uploads/40540f33f8436e1b5c211ec9da6beda9/gqe_direct_acquire.log)

```sh
Running experiments with subprocess sandbox
Starting parameter set execution with 20 sets remaining
Using 240s query timeout and 300s data load timeout
[2026-01-23 02:32:02.107] [gqe] [error] Error on worker 2: Test exception to check if a hang occurs
[2026-01-23 02:32:02.143] [gqe] [error] Error on worker 0: Test exception to check if a hang occurs
Parameter sets remaining: 20
Data load stage ended after 66.69s
Context creation ended after 0.00s
Query execution/validation iteration 0 ended after 240.27s
Timeout triggered - query did not complete within 240 seconds
Process still alive after terminate, trying sigkill
Subprocess exited with non-zero return code with 19 tasks remaining.
Subprocess Exit Code -15
Starting parameter set execution with 19 sets remaining
Using 240s query timeout and 300s data load timeout
[2026-01-23 02:37:16.454] [gqe] [error] Error on worker 2: Test exception to check if a hang occurs
[2026-01-23 02:37:16.490] [gqe] [error] Error on worker 0: Test exception to check if a hang occurs
Parameter sets remaining: 19
Data load stage ended after 66.59s
Context creation ended after 0.00s
Query execution/validation iteration 0 ended after 240.27s
Timeout triggered - query did not complete within 240 seconds
Process still alive after terminate, trying sigkill
Subprocess exited with non-zero return code with 18 tasks remaining.
Subprocess Exit Code -15
Starting parameter set execution with 18 sets remaining
```

The timeout goes away when using `gqe::utility::semaphore_acquire_guard` as shown by the sequence:

1. two worker threads acquire the semaphore
2. these threads throw the exception, which now releases the semaphore due to the guard
3. the other two workers acquire the semaphore, and also throw the exception
4. steps 1-3 repeat until all row groups are processed
5. the query fails, because the first worker throws the exception again during decompression
6. the process terminates
7. the benchmark harness immediately executes the next experiment configuration

This sequence is very fast, because no timeout occurs. For this reason, we will be using `semaphore_acquire_guard`.

Note that we expect the process to terminate already on step 3. This might be a bug in the benchmark harness.

[gqe_guard_acquire.log](/uploads/73f30a226be60412ca30dfcd02579237/gqe_guard_acquire.log)

```sh
Running query from handcoded with parameters debug_mem_usage=False, QueryExecutionContext(num_workers=4, num_partitions=16, use_overlap_mtx=False, join_use_hash_map_cache=False, read_use_zero_copy=False, join_use_unique_keys=True, join_use_perfect_hash=True, join_use_mark_join=True, use_partition_pruning=True, filter_use_like_shift_and=True, aggregation_use_perfect_hash=False, sut_info_id=None, query_info_ctx=QueryInfoContext(query_idx=6, query_str='6', query_source='handcoded', reference_file='/scratch/local/tpch/reference_results/sf100/q6.parquet', scale_factor=100.0, substrait_file=None, physical_plan_folder=None)), DataInfo(num_row_groups=32, compression_format='ans', compression_chunk_size=131072, zone_map_partition_size=200000, compression_ratio_threshold=1.0, secondary_compression_format='cascaded', secondary_compression_ratio_threshold=2.5, secondary_compression_multiplier_threshold=1.5, use_cpu_compression=False, compression_level=10, data_info_id=1, storage_device_kind='numa_pinned_memory', format='internal', location=None, not_null=False, identifier_type='TypeId.int32', char_type='char', decimal_type='float')[2026-01-23 02:53:02.540] [gqe] [error] Error on worker 1: Test exception to check if a hang occurs
[2026-01-23 02:53:02.576] [gqe] [error] Error on worker 3: Test exception to check if a hang occurs
[2026-01-23 02:53:02.612] [gqe] [error] Error on worker 0: Test exception to check if a hang occurs
[2026-01-23 02:53:02.648] [gqe] [error] Error on worker 2: Test exception to check if a hang occurs
[2026-01-23 02:53:02.702] [gqe] [error] Error on worker 2: Test exception to check if a hang occurs
[2026-01-23 02:53:02.738] [gqe] [error] Error on worker 0: Test exception to check if a hang occurs
[2026-01-23 02:53:02.774] [gqe] [error] Error on worker 1: Test exception to check if a hang occurs
[2026-01-23 02:53:02.810] [gqe] [error] Error on worker 3: Test exception to check if a hang occurs
[2026-01-23 02:53:02.866] [gqe] [error] Error on worker 0: Test exception to check if a hang occurs
[2026-01-23 02:53:02.902] [gqe] [error] Error on worker 1: Test exception to check if a hang occurs
[2026-01-23 02:53:02.938] [gqe] [error] Error on worker 2: Test exception to check if a hang occurs
[2026-01-23 02:53:02.974] [gqe] [error] Error on worker 3: Test exception to check if a hang occurs
[2026-01-23 02:53:03.029] [gqe] [error] Error on worker 3: Test exception to check if a hang occurs
[2026-01-23 02:53:03.065] [gqe] [error] Error on worker 0: Test exception to check if a hang occurs
[2026-01-23 02:53:03.101] [gqe] [error] Error on worker 2: Test exception to check if a hang occurs
[2026-01-23 02:53:03.138] [gqe] [error] Error on worker 1: Test exception to check if a hang occurs
[2026-01-23 02:53:03.193] [gqe] [error] Error on worker 0: Test exception to check if a hang occurs
[2026-01-23 02:53:03.229] [gqe] [error] Error on worker 3: Test exception to check if a hang occurs
[2026-01-23 02:53:03.265] [gqe] [error] Error on worker 1: Test exception to check if a hang occurs
[2026-01-23 02:53:03.302] [gqe] [error] Error on worker 2: Test exception to check if a hang occurs
[2026-01-23 02:53:03.356] [gqe] [error] Error on worker 0: Test exception to check if a hang occurs
[2026-01-23 02:53:03.392] [gqe] [error] Error on worker 1: Test exception to check if a hang occurs
[2026-01-23 02:53:03.428] [gqe] [error] Error on worker 2: Test exception to check if a hang occurs
[2026-01-23 02:53:03.464] [gqe] [error] Error on worker 3: Test exception to check if a hang occurs

No load required - data already in memory
Refreshing query execution context...
Running Q6...
Starting query Q6 repetition 0...
Error during query execution
RuntimeError: Test exception to check if a hang occurs
Running query from handcoded with parameters debug_mem_usage=False, QueryExecutionContext(num_workers=4, num_partitions=16, use_overlap_mtx=False, join_use_hash_map_cache=False, read_use_zero_copy=False, join_use_unique_keys=True, join_use_perfect_hash=True, join_use_mark_join=True, use_partition_pruning=True, filter_use_like_shift_and=True, aggregation_use_perfect_hash=True, sut_info_id=None, query_info_ctx=QueryInfoContext(query_idx=6, query_str='6', query_source='handcoded', reference_file='/scratch/local/tpch/reference_results/sf100/q6.parquet', scale_factor=100.0, substrait_file=None, physical_plan_folder=None)), DataInfo(num_row_groups=32, compression_format='ans', compression_chunk_size=131072, zone_map_partition_size=200000, compression_ratio_threshold=1.0, secondary_compression_format='cascaded', secondary_compression_ratio_threshold=2.5, secondary_compression_multiplier_threshold=1.5, use_cpu_compression=False, compression_level=10, data_info_id=1, storage_device_kind='numa_pinned_memory', format='internal', location=None, not_null=False, identifier_type='TypeId.int32', char_type='char', decimal_type='float')
No load required - data already in memory
```

## References

*The list of relevant papers, external links, etc.*

## Draft MR submission checklist

*Only for draft MRs: The list of points to be completed by author before the submitting MR for review.*

## Review checklist

(to be signed off by the reviewer)

 - [ ] Assigned self as reviewer in GitLab sidebar.
 - [ ] MR branch is in the `DevTech-Compute/gqe` repository (i.e., not a fork),
       and is prefixed with `$user-`.
   - Exception: Author has not been granted write permissions.
 - [ ] MR title is ["syntactically correct"](https://cbea.ms/git-commit). E.g.,
       "Optimize the aggregate operator for high group cardinality".
   - Less than 50 chars.
   - Capitalized.
   - Imperative mood.
   - Descriptive of the change.
 - [ ] MR goal, problem, and approach make sense to me (as described above).
 - [ ] MR is self-contained. I.e., doesn't rely on follow-up MRs to be
       minimially functional.
 - [ ] MR solves *one* (sub-)issue. Big issue is split into multiple
       self-contained MRs.
 - [ ] All source code files include [the Apache-2.0 license header](https://confluence.nvidia.com/display/LEG/Apache+2.0) and year is up-to-date.
 - [ ] Code style adheres to the [C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines) and [libcudf developer guidelines](https://github.com/rapidsai/cudf/blob/main/cpp/doxygen/developer_guide/DEVELOPER_GUIDE.md).
   - MLIR code instead adheres to the [LLVM coding standards](https://llvm.org/docs/CodingStandards.html).
 - [ ] Code is DRY. I.e., uses existing GQE / cuDF / MLIR infrastructure and
       utilities.
 - [ ] Code is documented.
   - [Doxygen API comments](https://github.com/rapidsai/cudf/blob/main/cpp/doxygen/developer_guide/DOCUMENTATION.md).
   - Algorithm / data structure description (if relevant).
 - [ ] Code includes CI unit and/or integration tests (if relevant).
 - [ ] MR is tested (see section Tests) and doesn't break the gqe-python main
       branch.
 - [ ] Stale MR branches are cleaned up. E.g., `this-MR-branch-v1`.