Fix: add subexpression visit (Devtech-Compute/gqe!377)
## Goal and reason

Add subquery expression evaluation in `expression_evaluator` .

## Problem statement

When build gqe, I experienced such errors: 

`/builds/Devtech-Compute/gqe/src/../include/gqe/executor/eval.hpp(55): error #611-D: overloaded virtual function "gqe::expression_visitor::visit" is only partially overridden in class "gqe::expression_evaluator" class expression_evaluator : public expression_visitor {` 

Suspect originally it was warnings, but we treat warnings as errors so far, we explicitly override this method.

## Solution approach

Add the override method for subquery expression.

## Alternative approaches

There seems to be no good solution so far.

## Impact (feature / bug / performance)

Passed all tests.

## References

No,

## Review checklist

(to be signed off by the reviewer)

- [x] Assigned self as reviewer in GitLab sidebar.
- [x] MR branch is in the `DevTech-Compute/gqe` repository (i.e., not a fork), and is prefixed with `$user-`.
  - Exception: Author has not been granted write permissions.
- [x] MR title is ["syntactically correct"](https://cbea.ms/git-commit). E.g., "Optimize the aggregate operator for high group cardinality".
  - Less than 50 chars.
  - Capitalized.
  - Imperative mood.
  - Descriptive of the change.
- [x] MR goal, problem, and approach make sense to me (as described above).
- [x] MR is self-contained. I.e., doesn't rely on follow-up MRs to be minimially functional.
- [x] MR solves _one_ (sub-)issue. Big issue is split into multiple self-contained MRs.
- [x] All files include [the NVIDIA copyright header](https://confluence.nvidia.com/display/LEG/NVIDIA+Proprietary) and year is up-to-date.
- [x] Code style adheres to the [C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines) and [libcudf developer guidelines](https://github.com/rapidsai/cudf/blob/main/cpp/doxygen/developer_guide/DEVELOPER_GUIDE.md).
  - MLIR code instead adheres to the [LLVM coding standards](https://llvm.org/docs/CodingStandards.html).
- [x] Code is DRY. I.e., uses existing GQE / cuDF / MLIR infrastructure and utilities.
- [x] Code is documented.
  - [Doxygen API comments](https://github.com/rapidsai/cudf/blob/main/cpp/doxygen/developer_guide/DOCUMENTATION.md).
  - Algorithm / data structure description (if relevant).
- [x] Code includes CI unit and/or integration tests (if relevant).
- [x] MR is tested (see section Tests) and doesn't break the gqe-python main branch.
- [x] Stale MR branches are cleaned up. E.g., `this-MR-branch-v1`.